### ISSUE TITLE
enumeration incomplète

### ISSUE THREAD

**Issue by benjaminderei** [atmjoy/AtmFlip#2]
https://github.com/atmjoy/AtmFlip/blob/7a80099d0a404cd5de9d5be903d119d0de9a756f/Firmware/hid_input.c#L219

ReportBuffer[0] ... 1 ...2 ...3 ... PAS DE 4 .... 5.... 6 ... 7

Normal ?

**Comment by atmjoy** [comment]
oui ,dans usbHidReportDescriptor
    0x75, 0x08,                    //     REPORT_SIZE (8)
    0x95, 0x03,                    //     REPORT_COUNT (3)
comme ReportBuffer sert aussi pour la partie clavier et eeprom , gardé la même variable
