### ISSUE TITLE
initee qui traine

### ISSUE THREAD

**Issue by benjaminderei** [atmjoy/AtmFlip#5]
https://github.com/atmjoy/AtmFlip/blob/876df6a71fda5b161be93e37f18e8c7ad5c748fa/Firmware/main.c#L296

Je sais pas si c'est toi ou moi mais ca va fatiguer l'eeprom pour rien et en plus ecraser les reglages a chaque fois :) !

**Comment by atmjoy** [comment]
en fait j'utilise la fonction eeprom_update_byte qui avant d’écrire lit l'eeprom et ecris que si la valeur lue est différente de celle a écrire . 
et bug initEE résolu mettrait a jour le github
